Also fixed by CVE-2019-9740.patch
https://bugs.python.org/issue35906#msg339842
